// Magnertia ERP — Mock data (Financial Management)

import type {
  AccountNode,
  PayableInvoice,
  ReceivableInvoice,
  TransactionRecord,
} from "@/services/types";

export const company = {
  name: "Magnertia",
  tagline: "EV Manufacturing",
  currency: "$",
  fiscalYear: "FY 2024-25",
};

/* -------- Dashboard headline KPIs (match reference exactly) -------- */
export const dashKpis = {
  totalRevenue: 24_580_000,
  netProfit: 4_320_000,
  totalExpenses: 18_760_000,
  cashBalance: 6_780_000,
  currentRatio: 2.35,
  currentRatioPY: 2.18,
};

/* -------- Revenue vs Expenses Trend (Apr'24 → Mar'25) -------- */
export const revenueExpenseTrend = [
  { month: "Apr '24", revenue: 2_100_000, expenses: 1_600_000, netProfit: 500_000 },
  { month: "May '24", revenue: 2_300_000, expenses: 1_700_000, netProfit: 600_000 },
  { month: "Jun '24", revenue: 2_000_000, expenses: 1_500_000, netProfit: 500_000 },
  { month: "Jul '24", revenue: 2_200_000, expenses: 1_800_000, netProfit: 400_000 },
  { month: "Aug '24", revenue: 2_400_000, expenses: 1_900_000, netProfit: 500_000 },
  { month: "Sep '24", revenue: 2_100_000, expenses: 1_700_000, netProfit: 400_000 },
  { month: "Oct '24", revenue: 2_500_000, expenses: 1_900_000, netProfit: 600_000 },
  { month: "Nov '24", revenue: 2_600_000, expenses: 2_000_000, netProfit: 600_000 },
  { month: "Dec '24", revenue: 2_800_000, expenses: 2_100_000, netProfit: 700_000 },
  { month: "Jan '25", revenue: 3_800_000, expenses: 2_900_000, netProfit: 900_000 },
  { month: "Feb '25", revenue: 4_200_000, expenses: 3_100_000, netProfit: 1_100_000 },
  { month: "Mar '25", revenue: 4_600_000, expenses: 3_300_000, netProfit: 1_300_000 },
];

export const cashFlowSummary = [
  { label: "Cash from Operating Activities", value: 8_450_000 },
  { label: "Cash from Investing Activities", value: -2_150_000 },
  { label: "Cash from Financing Activities", value: -1_320_000 },
];
export const netCashFlow = 4_980_000;

export const expenseDistribution = [
  { name: "Cost of Goods Sold", value: 35, color: "#0A3C75" },
  { name: "Operating Expenses", value: 25, color: "#336B9F" },
  { name: "Employee Expenses", value: 20, color: "#729FC9" },
  { name: "Marketing & Sales", value: 10, color: "#B2C9DF" },
  { name: "Other Expenses", value: 10, color: "#E2D9C5" },
];

export const agingReceivable = {
  total: 7_650_000,
  buckets: [
    { bucket: "0 - 30 Days", amount: 2_850_000, pct: 37.3, color: "#0A3C75" },
    { bucket: "31 - 60 Days", amount: 1_900_000, pct: 24.8, color: "#336B9F" },
    { bucket: "61 - 90 Days", amount: 1_350_000, pct: 17.6, color: "#729FC9" },
    { bucket: "91 - 120 Days", amount: 850_000, pct: 11.1, color: "#B2C9DF" },
    { bucket: "120+ Days", amount: 700_000, pct: 9.2, color: "#E2D9C5" },
  ],
};

export const agingPayable = {
  total: 5_420_000,
  buckets: [
    { bucket: "0 - 30 Days", amount: 2_100_000, pct: 38.7, color: "#0A3C75" },
    { bucket: "31 - 60 Days", amount: 1_500_000, pct: 27.7, color: "#336B9F" },
    { bucket: "61 - 90 Days", amount: 1_000_000, pct: 18.5, color: "#729FC9" },
    { bucket: "91 - 120 Days", amount: 550_000, pct: 10.1, color: "#B2C9DF" },
    { bucket: "120+ Days", amount: 270_000, pct: 9.0, color: "#E2D9C5" },
  ],
};

export const financialInsightsRaw = {
  grossMargin: { value: 42.6, deltaPct: 3.8, direction: "up" as const, tone: "positive" as const },
  operatingMargin: {
    value: 17.6,
    deltaPct: 2.1,
    direction: "up" as const,
    tone: "positive" as const,
  },
  expenseRatio: {
    value: 76.4,
    deltaPct: 1.7,
    direction: "down" as const,
    tone: "negative" as const,
  },
  dso: { value: 38, deltaDays: 4, direction: "down" as const, tone: "positive" as const },
  dpo: { value: 42, deltaDays: 3, direction: "up" as const, tone: "negative" as const },
  cashConversionCycle: {
    value: 36,
    deltaDays: 1,
    direction: "down" as const,
    tone: "positive" as const,
  },
};

export const recentTxns = [
  { date: "Today", ref: "INV-10034", description: "Invoice to Acme Corp.", amount: 45_600 },
  { date: "Today", ref: "PAY-20021", description: "Payment to ABC Supplies", amount: -12_450 },
  { date: "Today", ref: "JE-30015", description: "Journal Entry", amount: 8_750 },
  { date: "Today", ref: "BILL-40011", description: "Bill from Global Services", amount: -7_850 },
  { date: "Today", ref: "RCPT-50009", description: "Payment from Beta Ltd.", amount: 22_300 },
];

/* -------- Transactions module -------- */
export const transactionsKpisRaw = {
  totalTransactions: 2_548,
  totalAmount: 124_750_000,
  transactionsToday: { count: 18, amount: 2_350_000 },
  thisMonth: { count: 256, amount: 18_760_000 },
  pendingApproval: { count: 32, amount: 1_920_000 },
};

// Ordered newest-first, matching the mockup. The first 10 rows are the exact
// rows shown in the reference screenshot; the rest extend the same fiscal
// year for pagination/filtering/sorting to have something real to do.
export const allTransactions: TransactionRecord[] = [
  {
    date: "May 20, 2025",
    ref: "INV-10034",
    description: "Invoice to Acme Corp.",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 45_600,
    status: "Posted",
    counterparty: "Acme Corp.",
    dueDate: "Jun 19, 2025",
  },
  {
    date: "May 20, 2025",
    ref: "PAY-20021",
    description: "Payment to ABC Supplies",
    type: "Payment",
    account: "Accounts Payable",
    amount: -12_450,
    status: "Posted",
    counterparty: "ABC Supplies",
  },
  {
    date: "May 19, 2025",
    ref: "JE-30015",
    description: "Journal Entry",
    type: "Journal Entry",
    account: "General Ledger",
    amount: 8_750,
    status: "Posted",
  },
  {
    date: "May 19, 2025",
    ref: "BILL-40011",
    description: "Bill from Global Services",
    type: "Bill",
    account: "Accounts Payable",
    amount: -7_850,
    status: "Approved",
    counterparty: "Global Services",
    dueDate: "Jun 18, 2025",
  },
  {
    date: "May 18, 2025",
    ref: "RCPT-50009",
    description: "Payment from Beta Ltd.",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 22_300,
    status: "Posted",
    counterparty: "Beta Ltd.",
  },
  {
    date: "May 18, 2025",
    ref: "JE-30014",
    description: "Depreciation Entry - May",
    type: "Journal Entry",
    account: "Fixed Assets",
    amount: -3_240,
    status: "Posted",
  },
  {
    date: "May 17, 2025",
    ref: "INV-10033",
    description: "Invoice to Delta Solutions",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 18_900,
    status: "Pending",
    counterparty: "Delta Solutions",
    dueDate: "Jun 16, 2025",
  },
  {
    date: "May 17, 2025",
    ref: "PAY-20020",
    description: "Payment to Office Mart",
    type: "Payment",
    account: "Accounts Payable",
    amount: -1_250,
    status: "Posted",
    counterparty: "Office Mart",
  },
  {
    date: "May 16, 2025",
    ref: "RCPT-50008",
    description: "Payment from Gamma Inc.",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 15_600,
    status: "Posted",
    counterparty: "Gamma Inc.",
  },
  {
    date: "May 16, 2025",
    ref: "BILL-40010",
    description: "Bill from Utility Services",
    type: "Bill",
    account: "Accounts Payable",
    amount: -980,
    status: "Approved",
    counterparty: "Utility Services",
    dueDate: "Jun 15, 2025",
  },
  {
    date: "May 15, 2025",
    ref: "INV-10032",
    description: "Invoice to Gamma Industries",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 62_400,
    status: "Posted",
    counterparty: "Gamma Industries",
    dueDate: "Jun 14, 2025",
  },
  {
    date: "May 15, 2025",
    ref: "PAY-20019",
    description: "Payment to Siemens India",
    type: "Payment",
    account: "Accounts Payable",
    amount: -68_400,
    status: "Posted",
    counterparty: "Siemens India",
  },
  {
    date: "May 14, 2025",
    ref: "JE-30013",
    description: "Journal Entry",
    type: "Journal Entry",
    account: "General Ledger",
    amount: 14_200,
    status: "Posted",
  },
  {
    date: "May 14, 2025",
    ref: "BILL-40009",
    description: "Bill from Bosch Components",
    type: "Bill",
    account: "Accounts Payable",
    amount: -18_400,
    status: "Pending",
    counterparty: "Bosch Components",
    dueDate: "Jun 13, 2025",
  },
  {
    date: "May 13, 2025",
    ref: "RCPT-50007",
    description: "Payment from Delta Mobility",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 18_420,
    status: "Posted",
    counterparty: "Delta Mobility",
  },
  {
    date: "May 12, 2025",
    ref: "INV-10031",
    description: "Invoice to Epsilon Fleet",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 92_000,
    status: "Approved",
    counterparty: "Epsilon Fleet",
    dueDate: "Jun 11, 2025",
  },
  {
    date: "May 12, 2025",
    ref: "PAY-20018",
    description: "Payment to DLF Properties",
    type: "Payment",
    account: "Accounts Payable",
    amount: -8_450,
    status: "Posted",
    counterparty: "DLF Properties",
  },
  {
    date: "May 10, 2025",
    ref: "JE-30012",
    description: "Payroll Accrual - May",
    type: "Journal Entry",
    account: "General Ledger",
    amount: -32_000,
    status: "Posted",
  },
  {
    date: "May 9, 2025",
    ref: "BILL-40008",
    description: "Bill from ABB Power Grids",
    type: "Bill",
    account: "Accounts Payable",
    amount: -41_200,
    status: "Posted",
    counterparty: "ABB Power Grids",
    dueDate: "Jun 8, 2025",
  },
  {
    date: "May 8, 2025",
    ref: "RCPT-50006",
    description: "Payment from Zeta Logistics",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 28_560,
    status: "Posted",
    counterparty: "Zeta Logistics",
  },
  {
    date: "May 6, 2025",
    ref: "INV-10030",
    description: "Invoice to Acme Corp.",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 34_800,
    status: "Posted",
    counterparty: "Acme Corp.",
    dueDate: "Jun 5, 2025",
  },
  {
    date: "May 5, 2025",
    ref: "PAY-20017",
    description: "Payment to Schneider Electric",
    type: "Payment",
    account: "Accounts Payable",
    amount: -17_800,
    status: "Approved",
    counterparty: "Schneider Electric",
  },
  {
    date: "May 4, 2025",
    ref: "JE-30011",
    description: "Journal Entry",
    type: "Journal Entry",
    account: "General Ledger",
    amount: 6_200,
    status: "Posted",
  },
  {
    date: "May 3, 2025",
    ref: "BILL-40007",
    description: "Bill from Delta Electronics",
    type: "Bill",
    account: "Accounts Payable",
    amount: -29_500,
    status: "Pending",
    counterparty: "Delta Electronics",
    dueDate: "Jun 2, 2025",
  },
  {
    date: "May 2, 2025",
    ref: "RCPT-50005",
    description: "Payment from Beta Ltd.",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 19_750,
    status: "Posted",
    counterparty: "Beta Ltd.",
  },
  {
    date: "Apr 30, 2025",
    ref: "INV-10029",
    description: "Invoice to Gamma Industries",
    type: "Invoice",
    account: "Accounts Receivable",
    amount: 48_600,
    status: "Posted",
    counterparty: "Gamma Industries",
    dueDate: "May 30, 2025",
  },
  {
    date: "Apr 28, 2025",
    ref: "JE-30010",
    description: "Depreciation Entry - Apr",
    type: "Journal Entry",
    account: "Fixed Assets",
    amount: -3_180,
    status: "Posted",
  },
  {
    date: "Apr 26, 2025",
    ref: "PAY-20016",
    description: "Payment to Panasonic Cells",
    type: "Payment",
    account: "Accounts Payable",
    amount: -124_800,
    status: "Posted",
    counterparty: "Panasonic Cells",
  },
  {
    date: "Apr 24, 2025",
    ref: "BILL-40006",
    description: "Bill from Google Ads",
    type: "Bill",
    account: "Accounts Payable",
    amount: -4_500,
    status: "Posted",
    counterparty: "Google Ads",
    dueDate: "May 24, 2025",
  },
  {
    date: "Apr 22, 2025",
    ref: "RCPT-50004",
    description: "Payment from Delta Mobility",
    type: "Receipt",
    account: "Accounts Receivable",
    amount: 92_000,
    status: "Posted",
    counterparty: "Delta Mobility",
  },
];

/* -------- General Ledger module -------- */
// Headline KPIs are independent mock constants, decoupled from the chart of
// accounts tree below (same pattern as Transactions' totalTransactions) —
// and independent of Dashboard's netProfit (see architecture.md: the two
// mockups disagree on Net Income/Net Profit and we don't force them to match).
export const ledgerKpisRaw = {
  totalAccounts: 1_245,
  totalDebits: 1_248_750_000,
  totalCredits: 1_248_750_000,
  netIncome: 24_320_000,
  currentPeriod: "May 2025",
  periodStatus: "Open" as const,
};

export const accountDistribution = [
  { name: "Assets", value: 48, color: "#0A3C75" },
  { name: "Liabilities", value: 26, color: "#3B82F6" },
  { name: "Equity", value: 15, color: "#F59E0B" },
  { name: "Revenue", value: 7, color: "#22C55E" },
  { name: "Expenses", value: 4, color: "#9CA3AF" },
];

// Chart of Accounts tree. Figures for Assets/Liabilities match the reference
// mockup exactly (including its own header-vs-children rounding — we don't
// "fix" numbers the mockup itself shows inconsistently). Equity/Revenue/
// Expenses aren't shown in the mockup (cut off below the fold), so those are
// original and constructed to balance debit = credit exactly at the leaf
// level, matching what a real trial balance should do.
export const chartOfAccounts: AccountNode[] = [
  {
    code: "1000",
    name: "Assets",
    type: "Asset",
    group: "Assets",
    normalBalance: "Debit",
    debit: 890_450_000,
    credit: 342_180_000,
    status: "Active",
    children: [
      {
        code: "1100",
        name: "Current Assets",
        type: "Asset",
        group: "Current Assets",
        normalBalance: "Debit",
        debit: 456_320_000,
        credit: 198_760_000,
        status: "Active",
        children: [
          {
            code: "1110",
            name: "Cash and Cash Equivalents",
            type: "Asset",
            group: "Current Assets",
            normalBalance: "Debit",
            debit: 185_450_000,
            credit: 95_320_000,
            status: "Active",
            openingBalance: 62_000_000,
          },
          {
            code: "1120",
            name: "Accounts Receivable",
            type: "Asset",
            group: "Current Assets",
            normalBalance: "Debit",
            debit: 145_600_000,
            credit: 42_300_000,
            status: "Active",
            openingBalance: 78_450_000,
          },
          {
            code: "1130",
            name: "Inventory",
            type: "Asset",
            group: "Current Assets",
            normalBalance: "Debit",
            debit: 98_750_000,
            credit: 36_140_000,
            status: "Active",
            openingBalance: 41_000_000,
          },
          {
            code: "1140",
            name: "Prepaid Expenses",
            type: "Asset",
            group: "Current Assets",
            normalBalance: "Debit",
            debit: 26_520_000,
            credit: 24_150_000,
            status: "Active",
            openingBalance: 1_800_000,
          },
        ],
      },
      {
        code: "1200",
        name: "Non-Current Assets",
        type: "Asset",
        group: "Non-Current Assets",
        normalBalance: "Debit",
        debit: 434_130_000,
        credit: 143_420_000,
        status: "Active",
        children: [
          {
            code: "1210",
            name: "Property, Plant & Equipment",
            type: "Asset",
            group: "Non-Current Assets",
            normalBalance: "Debit",
            debit: 378_200_000,
            credit: 112_340_000,
            status: "Active",
            openingBalance: 210_000_000,
          },
          {
            code: "1220",
            name: "Accumulated Depreciation",
            type: "Asset",
            group: "Non-Current Assets",
            normalBalance: "Debit",
            debit: 0,
            credit: 72_150_000,
            status: "Active",
            openingBalance: -58_000_000,
          },
          {
            code: "1230",
            name: "Intangible Assets",
            type: "Asset",
            group: "Non-Current Assets",
            normalBalance: "Debit",
            debit: 45_930_000,
            credit: 12_080_000,
            status: "Active",
            openingBalance: 27_000_000,
          },
          {
            code: "1240",
            name: "Other Assets",
            type: "Asset",
            group: "Non-Current Assets",
            normalBalance: "Debit",
            debit: 10_000_000,
            credit: 6_850_000,
            status: "Active",
            openingBalance: 2_600_000,
          },
        ],
      },
    ],
  },
  {
    code: "2000",
    name: "Liabilities",
    type: "Liability",
    group: "Liabilities",
    normalBalance: "Credit",
    debit: 312_680_000,
    credit: 567_340_000,
    status: "Active",
    children: [
      {
        code: "2100",
        name: "Current Liabilities",
        type: "Liability",
        group: "Current Liabilities",
        normalBalance: "Credit",
        debit: 245_120_000,
        credit: 312_450_000,
        status: "Active",
        children: [
          {
            code: "2110",
            name: "Accounts Payable",
            type: "Liability",
            group: "Current Liabilities",
            normalBalance: "Credit",
            debit: 125_400_000,
            credit: 185_600_000,
            status: "Active",
            openingBalance: -48_000_000,
          },
          {
            code: "2120",
            name: "Short-term Loans",
            type: "Liability",
            group: "Current Liabilities",
            normalBalance: "Credit",
            debit: 65_300_000,
            credit: 78_900_000,
            status: "Active",
            openingBalance: -9_000_000,
          },
        ],
      },
    ],
  },
  {
    code: "3000",
    name: "Equity",
    type: "Equity",
    group: "Equity",
    normalBalance: "Credit",
    debit: 30_000_000,
    credit: 300_000_000,
    status: "Active",
    children: [
      {
        code: "3100",
        name: "Common Stock",
        type: "Equity",
        group: "Equity",
        normalBalance: "Credit",
        debit: 10_000_000,
        credit: 200_000_000,
        status: "Active",
        openingBalance: -170_000_000,
      },
      {
        code: "3200",
        name: "Retained Earnings",
        type: "Equity",
        group: "Equity",
        normalBalance: "Credit",
        debit: 20_000_000,
        credit: 100_000_000,
        status: "Active",
        openingBalance: -55_000_000,
      },
    ],
  },
  {
    code: "4000",
    name: "Revenue",
    type: "Revenue",
    group: "Revenue",
    normalBalance: "Credit",
    debit: 15_000_000,
    credit: 250_000_000,
    status: "Active",
    children: [
      {
        code: "4100",
        name: "Product Revenue",
        type: "Revenue",
        group: "Revenue",
        normalBalance: "Credit",
        debit: 10_000_000,
        credit: 170_000_000,
        status: "Active",
        openingBalance: -140_000_000,
      },
      {
        code: "4200",
        name: "Service Revenue",
        type: "Revenue",
        group: "Revenue",
        normalBalance: "Credit",
        debit: 5_000_000,
        credit: 80_000_000,
        status: "Active",
        openingBalance: -65_000_000,
      },
    ],
  },
  {
    code: "5000",
    name: "Expenses",
    type: "Expense",
    group: "Expenses",
    normalBalance: "Debit",
    debit: 110_000_000,
    credit: 20_320_000,
    status: "Active",
    children: [
      {
        code: "5100",
        name: "Operating Expenses",
        type: "Expense",
        group: "Expenses",
        normalBalance: "Debit",
        debit: 70_000_000,
        credit: 12_000_000,
        status: "Active",
        openingBalance: 48_000_000,
      },
      {
        code: "5200",
        name: "Cost of Goods Sold",
        type: "Expense",
        group: "Expenses",
        normalBalance: "Debit",
        debit: 40_000_000,
        credit: 8_320_000,
        status: "Active",
        openingBalance: 26_000_000,
      },
    ],
  },
];

// Journal history per leaf account (for the Account Activity tab). Only a
// handful of accounts have hand-authored entries; others fall back to a
// generated placeholder (see generalLedgerService.fetchTransactionHistory).
export const accountActivity: Record<
  string,
  {
    date: string;
    ref: string;
    description: string;
    debit: number;
    credit: number;
    balance: number;
  }[]
> = {
  "1120": [
    {
      date: "May 20, 2025",
      ref: "INV-10034",
      description: "Invoice to Acme Corp.",
      debit: 45_600,
      credit: 0,
      balance: 103_345_600,
    },
    {
      date: "May 18, 2025",
      ref: "RCPT-50009",
      description: "Payment from Beta Ltd.",
      debit: 0,
      credit: 22_300,
      balance: 103_300_000,
    },
    {
      date: "May 17, 2025",
      ref: "INV-10033",
      description: "Invoice to Delta Solutions",
      debit: 18_900,
      credit: 0,
      balance: 103_322_300,
    },
    {
      date: "May 16, 2025",
      ref: "RCPT-50008",
      description: "Payment from Gamma Inc.",
      debit: 0,
      credit: 15_600,
      balance: 103_303_400,
    },
    {
      date: "May 6, 2025",
      ref: "INV-10030",
      description: "Invoice to Acme Corp.",
      debit: 34_800,
      credit: 0,
      balance: 103_319_000,
    },
  ],
};

/* -------- Accounts Payable module -------- */
// Headline KPIs / summary panels are independent mock constants matching the
// reference mockup exactly, decoupled from the smaller payableInvoices list
// below — same "headline vs. backing list" split used by every module's
// summary panels so far (Dashboard's expenseDistribution, General Ledger's
// accountDistribution, ...). Only the paginated invoice list itself is a
// real, honestly-sized dataset with its own real total.
export const apKpisRaw = {
  totalPayables: 3_245_780,
  overdueAmount: 785_430,
  overduePctOfTotal: 24.18,
  dueWithin30Days: 1_245_320,
  dueWithin30PctOfTotal: 38.33,
  paidThisMonth: 1_568_940,
  openInvoices: 156,
};

// Page-scoped semantic aging palette (green -> gray = fresher -> older),
// deliberately different from the Dashboard's monochrome blue-shades aging
// donuts — see architecture.md's "Aging bucket color is page-scoped" note.
export const apAgingSummary = {
  total: 3_245_780,
  buckets: [
    { bucket: "0 - 30 Days", amount: 1_250_000, pct: 38.33, color: "#22C55E" },
    { bucket: "31 - 60 Days", amount: 850_200, pct: 26.17, color: "#3B82F6" },
    { bucket: "61 - 90 Days", amount: 560_400, pct: 17.25, color: "#F59E0B" },
    { bucket: "91 - 120 Days", amount: 320_100, pct: 9.85, color: "#EF4444" },
    { bucket: "120+ Days", amount: 260_080, pct: 8.4, color: "#9CA3AF" },
  ],
};

export const apTopVendors = [
  { vendor: "Acme Corp.", amount: 785_430 },
  { vendor: "Global Supplies Co.", amount: 532_750 },
  { vendor: "Beta Ltd.", amount: 345_600 },
  { vendor: "Delta Solutions", amount: 318_900 },
  { vendor: "Techno Services Ltd.", amount: 245_780 },
];

export const apPaymentSummary = {
  totalPaid: 1_568_940,
  averagePayment: 37_355.71,
  totalPayments: 42,
  discountsTaken: 12_450,
};

// Note on Acme Corp.: this same reference (INV-10034, $45,600) appears as an
// Accounts Receivable invoice (Acme Corp. as customer) in the Dashboard and
// Transactions modules. Here it's an Accounts Payable invoice (Acme Corp. as
// vendor). Independent mock datasets, not reconciled — same "treat as
// independent mock figures" call as Net Income vs. Net Profit in the General
// Ledger module. Don't "fix" this into a single consistent Acme Corp. record.
export const payableInvoices: PayableInvoice[] = [
  {
    invoiceNo: "INV-10034",
    vendor: "Acme Corp.",
    invoiceDate: "May 20, 2025",
    dueDate: "Jun 19, 2025",
    amount: 45_600,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10033",
    vendor: "Delta Solutions",
    invoiceDate: "May 17, 2025",
    dueDate: "Jun 16, 2025",
    amount: 18_900,
    status: "Due Soon",
    dueAmount: 18_900,
    approved: false,
  },
  {
    invoiceNo: "INV-10032",
    vendor: "Global Supplies Co.",
    invoiceDate: "May 16, 2025",
    dueDate: "Jun 15, 2025",
    amount: 22_750,
    status: "Overdue",
    dueAmount: 22_750,
    approved: true,
  },
  {
    invoiceNo: "INV-10031",
    vendor: "Office Mart",
    invoiceDate: "May 15, 2025",
    dueDate: "Jun 14, 2025",
    amount: 1_250,
    status: "Overdue",
    dueAmount: 1_250,
    approved: true,
  },
  {
    invoiceNo: "INV-10030",
    vendor: "Techno Services Ltd.",
    invoiceDate: "May 14, 2025",
    dueDate: "Jun 13, 2025",
    amount: 12_480,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10029",
    vendor: "Beta Ltd.",
    invoiceDate: "May 13, 2025",
    dueDate: "Jun 12, 2025",
    amount: 22_300,
    status: "Overdue",
    dueAmount: 22_300,
    approved: true,
  },
  {
    invoiceNo: "INV-10028",
    vendor: "Utility Services",
    invoiceDate: "May 12, 2025",
    dueDate: "Jun 11, 2025",
    amount: 9_850,
    status: "Due Soon",
    dueAmount: 9_850,
    approved: false,
  },
  {
    invoiceNo: "INV-10027",
    vendor: "Packaging World",
    invoiceDate: "May 10, 2025",
    dueDate: "Jun 9, 2025",
    amount: 7_450,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10026",
    vendor: "ABC Supplies",
    invoiceDate: "May 9, 2025",
    dueDate: "Jun 8, 2025",
    amount: 12_450,
    status: "Overdue",
    dueAmount: 12_450,
    approved: true,
  },
  {
    invoiceNo: "INV-10025",
    vendor: "Paper & Co.",
    invoiceDate: "May 8, 2025",
    dueDate: "Jun 7, 2025",
    amount: 3_750,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10024",
    vendor: "Global Supplies Co.",
    invoiceDate: "May 6, 2025",
    dueDate: "Jun 5, 2025",
    amount: 62_400,
    status: "Overdue",
    dueAmount: 62_400,
    approved: true,
  },
  {
    invoiceNo: "INV-10023",
    vendor: "Beta Ltd.",
    invoiceDate: "May 5, 2025",
    dueDate: "Jun 4, 2025",
    amount: 18_420,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10022",
    vendor: "Techno Services Ltd.",
    invoiceDate: "May 4, 2025",
    dueDate: "Jun 3, 2025",
    amount: 34_800,
    status: "Due Soon",
    dueAmount: 34_800,
    approved: false,
  },
  {
    invoiceNo: "INV-10021",
    vendor: "Acme Corp.",
    invoiceDate: "May 3, 2025",
    dueDate: "Jun 2, 2025",
    amount: 8_450,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10020",
    vendor: "Delta Solutions",
    invoiceDate: "May 2, 2025",
    dueDate: "Jun 1, 2025",
    amount: 29_500,
    status: "Overdue",
    dueAmount: 29_500,
    approved: true,
  },
  {
    invoiceNo: "INV-10019",
    vendor: "Office Mart",
    invoiceDate: "Apr 30, 2025",
    dueDate: "May 30, 2025",
    amount: 1_980,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10018",
    vendor: "ABC Supplies",
    invoiceDate: "Apr 28, 2025",
    dueDate: "May 28, 2025",
    amount: 15_600,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10017",
    vendor: "Utility Services",
    invoiceDate: "Apr 26, 2025",
    dueDate: "May 26, 2025",
    amount: 6_200,
    status: "Canceled",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10016",
    vendor: "Packaging World",
    invoiceDate: "Apr 24, 2025",
    dueDate: "May 24, 2025",
    amount: 9_750,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10015",
    vendor: "Paper & Co.",
    invoiceDate: "Apr 22, 2025",
    dueDate: "May 22, 2025",
    amount: 2_480,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10014",
    vendor: "Global Supplies Co.",
    invoiceDate: "Apr 20, 2025",
    dueDate: "May 20, 2025",
    amount: 48_600,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10013",
    vendor: "Beta Ltd.",
    invoiceDate: "Apr 18, 2025",
    dueDate: "May 18, 2025",
    amount: 124_800,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10012",
    vendor: "Techno Services Ltd.",
    invoiceDate: "Apr 16, 2025",
    dueDate: "May 16, 2025",
    amount: 4_500,
    status: "Canceled",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10011",
    vendor: "Acme Corp.",
    invoiceDate: "Apr 14, 2025",
    dueDate: "May 14, 2025",
    amount: 92_000,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10010",
    vendor: "Delta Solutions",
    invoiceDate: "Apr 12, 2025",
    dueDate: "May 12, 2025",
    amount: 17_800,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10009",
    vendor: "Office Mart",
    invoiceDate: "Apr 10, 2025",
    dueDate: "May 10, 2025",
    amount: 6_200,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10008",
    vendor: "ABC Supplies",
    invoiceDate: "Apr 8, 2025",
    dueDate: "May 8, 2025",
    amount: 29_500,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10007",
    vendor: "Utility Services",
    invoiceDate: "Apr 6, 2025",
    dueDate: "May 6, 2025",
    amount: 19_750,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10006",
    vendor: "Packaging World",
    invoiceDate: "Apr 4, 2025",
    dueDate: "May 4, 2025",
    amount: 48_600,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
  {
    invoiceNo: "INV-10005",
    vendor: "Paper & Co.",
    invoiceDate: "Apr 2, 2025",
    dueDate: "May 2, 2025",
    amount: 3_180,
    status: "Paid",
    dueAmount: 0,
    approved: true,
  },
];

export const apVendorDirectory: Record<
  string,
  {
    id: string;
    category: string;
    email: string;
    phone: string;
    paymentTerms: string;
    status: "Active" | "Inactive";
  }
> = {
  "Acme Corp.": {
    id: "VND-101",
    category: "Raw Materials",
    email: "accounts@acmecorp.com",
    phone: "+1 555-0101",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Delta Solutions": {
    id: "VND-102",
    category: "IT Services",
    email: "billing@deltasolutions.com",
    phone: "+1 555-0102",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Global Supplies Co.": {
    id: "VND-103",
    category: "Office Supplies",
    email: "ap@globalsupplies.com",
    phone: "+1 555-0103",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Office Mart": {
    id: "VND-104",
    category: "Office Supplies",
    email: "accounts@officemart.com",
    phone: "+1 555-0104",
    paymentTerms: "Net 15",
    status: "Active",
  },
  "Techno Services Ltd.": {
    id: "VND-105",
    category: "IT Services",
    email: "finance@technoservices.com",
    phone: "+1 555-0105",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Beta Ltd.": {
    id: "VND-106",
    category: "Manufacturing",
    email: "ap@betaltd.com",
    phone: "+1 555-0106",
    paymentTerms: "Net 45",
    status: "Active",
  },
  "Utility Services": {
    id: "VND-107",
    category: "Utilities",
    email: "billing@utilityservices.com",
    phone: "+1 555-0107",
    paymentTerms: "Net 15",
    status: "Active",
  },
  "Packaging World": {
    id: "VND-108",
    category: "Packaging",
    email: "accounts@packagingworld.com",
    phone: "+1 555-0108",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "ABC Supplies": {
    id: "VND-109",
    category: "Office Supplies",
    email: "ap@abcsupplies.com",
    phone: "+1 555-0109",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Paper & Co.": {
    id: "VND-110",
    category: "Office Supplies",
    email: "billing@paperco.com",
    phone: "+1 555-0110",
    paymentTerms: "Net 15",
    status: "Active",
  },
};

/* -------- Accounts Receivable module -------- */
// Headline KPIs / summary panels are independent mock constants matching the
// reference mockup exactly — same "headline vs. backing list" split used
// throughout (see architecture.md). Acme Corp. shows up a third time here
// with yet another invoice number/amount ($78,450, INV-20034) — independent
// of both its Dashboard/Transactions AR record and its Accounts Payable
// vendor record. Not reconciled, same as those.
export const arKpisRaw = {
  totalReceivables: 4_125_680,
  overdueAmount: 1_258_430,
  overduePctOfTotal: 30.52,
  dueWithin30Days: 1_842_750,
  dueWithin30PctOfTotal: 44.68,
  collectedThisMonth: 1_980_450,
  openInvoices: 218,
};

// Same page-scoped semantic aging palette as Accounts Payable's Aging
// Summary (green -> gray = fresher -> older) — both pages independently
// chose it because it signals collection risk, not because of a shared rule.
export const arAgingSummary = {
  total: 4_130_000,
  buckets: [
    { bucket: "0 - 30 Days", amount: 1_840_000, pct: 44.68, color: "#22C55E" },
    { bucket: "31 - 60 Days", amount: 1_020_000, pct: 24.75, color: "#3B82F6" },
    { bucket: "61 - 90 Days", amount: 640_250, pct: 15.54, color: "#F59E0B" },
    { bucket: "91 - 120 Days", amount: 352_100, pct: 8.54, color: "#EF4444" },
    { bucket: "120+ Days", amount: 258_430, pct: 6.26, color: "#9CA3AF" },
  ],
};

export const arTopCustomers = [
  { customer: "Acme Corp.", amount: 785_430 },
  { customer: "Global Industries Ltd.", amount: 632_750 },
  { customer: "Tech Solutions Inc.", amount: 468_900 },
  { customer: "Beta Ltd.", amount: 318_900 },
  { customer: "Delta Enterprises", amount: 245_780 },
];

export const arCollectionSummary = {
  billedAmount: 2_450_700,
  collectedAmount: 1_980_450,
  collectionPct: 80.85,
  avgDaysToCollect: 32,
};

// Bimonthly trend, Apr '24 -> Apr '25 (same 7-point cadence as General
// Ledger's Account Balance Trend chart).
export const receivableTrend = [
  { month: "Apr '24", totalReceivables: 2_300_000, collectedAmount: 820_000 },
  { month: "Jun '24", totalReceivables: 2_650_000, collectedAmount: 1_040_000 },
  { month: "Aug '24", totalReceivables: 2_580_000, collectedAmount: 1_180_000 },
  { month: "Oct '24", totalReceivables: 3_120_000, collectedAmount: 1_350_000 },
  { month: "Dec '24", totalReceivables: 3_450_000, collectedAmount: 1_520_000 },
  { month: "Feb '25", totalReceivables: 3_980_000, collectedAmount: 1_780_000 },
  { month: "Apr '25", totalReceivables: 4_530_000, collectedAmount: 2_310_000 },
];

// Ordered newest-first, matching the mockup. The first 10 rows are the exact
// rows shown in the reference screenshot; the rest extend the same fiscal
// year for pagination/filtering/sorting, including a couple of Credit Memos
// and a Canceled invoice so every tab has something to show.
export const receivableInvoices: ReceivableInvoice[] = [
  {
    invoiceNo: "INV-20034",
    customer: "Acme Corp.",
    invoiceDate: "May 20, 2025",
    dueDate: "Jun 19, 2025",
    amount: 78_450,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20033",
    customer: "Global Industries Ltd.",
    invoiceDate: "May 17, 2025",
    dueDate: "Jun 16, 2025",
    amount: 45_600,
    status: "Partially Paid",
    dueAmount: 12_500,
  },
  {
    invoiceNo: "INV-20032",
    customer: "Tech Solutions Inc.",
    invoiceDate: "May 16, 2025",
    dueDate: "Jun 15, 2025",
    amount: 32_750,
    status: "Overdue",
    dueAmount: 32_750,
  },
  {
    invoiceNo: "INV-20031",
    customer: "Beta Ltd.",
    invoiceDate: "May 15, 2025",
    dueDate: "Jun 14, 2025",
    amount: 18_900,
    status: "Overdue",
    dueAmount: 18_900,
  },
  {
    invoiceNo: "INV-20030",
    customer: "Delta Enterprises",
    invoiceDate: "May 14, 2025",
    dueDate: "Jun 13, 2025",
    amount: 28_450,
    status: "Due Soon",
    dueAmount: 28_450,
  },
  {
    invoiceNo: "INV-20029",
    customer: "Omega Pvt. Ltd.",
    invoiceDate: "May 13, 2025",
    dueDate: "Jun 12, 2025",
    amount: 56_780,
    status: "Partially Paid",
    dueAmount: 8_230,
  },
  {
    invoiceNo: "INV-20028",
    customer: "Bright Future LLC",
    invoiceDate: "May 12, 2025",
    dueDate: "Jun 11, 2025",
    amount: 24_750,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20027",
    customer: "Stellar Systems",
    invoiceDate: "May 10, 2025",
    dueDate: "Jun 9, 2025",
    amount: 22_600,
    status: "Overdue",
    dueAmount: 22_600,
  },
  {
    invoiceNo: "INV-20026",
    customer: "Prime Retailers",
    invoiceDate: "May 9, 2025",
    dueDate: "Jun 8, 2025",
    amount: 15_300,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20025",
    customer: "Visionary Works",
    invoiceDate: "May 8, 2025",
    dueDate: "Jun 7, 2025",
    amount: 12_450,
    status: "Due Soon",
    dueAmount: 12_450,
  },
  {
    invoiceNo: "INV-20024",
    customer: "Global Industries Ltd.",
    invoiceDate: "May 6, 2025",
    dueDate: "Jun 5, 2025",
    amount: 62_400,
    status: "Overdue",
    dueAmount: 62_400,
  },
  {
    invoiceNo: "INV-20023",
    customer: "Beta Ltd.",
    invoiceDate: "May 5, 2025",
    dueDate: "Jun 4, 2025",
    amount: 18_420,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20022",
    customer: "Tech Solutions Inc.",
    invoiceDate: "May 4, 2025",
    dueDate: "Jun 3, 2025",
    amount: 34_800,
    status: "Due Soon",
    dueAmount: 34_800,
  },
  {
    invoiceNo: "INV-20021",
    customer: "Acme Corp.",
    invoiceDate: "May 3, 2025",
    dueDate: "Jun 2, 2025",
    amount: 8_450,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20020",
    customer: "Delta Enterprises",
    invoiceDate: "May 2, 2025",
    dueDate: "Jun 1, 2025",
    amount: 29_500,
    status: "Overdue",
    dueAmount: 29_500,
  },
  {
    invoiceNo: "INV-20019",
    customer: "Omega Pvt. Ltd.",
    invoiceDate: "Apr 30, 2025",
    dueDate: "May 30, 2025",
    amount: 1_980,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20018",
    customer: "Stellar Systems",
    invoiceDate: "Apr 28, 2025",
    dueDate: "May 28, 2025",
    amount: 15_600,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "CM-3001",
    customer: "Bright Future LLC",
    invoiceDate: "Apr 26, 2025",
    dueDate: "Apr 26, 2025",
    amount: -3_200,
    status: "Credit Memo",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20016",
    customer: "Prime Retailers",
    invoiceDate: "Apr 24, 2025",
    dueDate: "May 24, 2025",
    amount: 9_750,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20015",
    customer: "Visionary Works",
    invoiceDate: "Apr 22, 2025",
    dueDate: "May 22, 2025",
    amount: 2_480,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20014",
    customer: "Global Industries Ltd.",
    invoiceDate: "Apr 20, 2025",
    dueDate: "May 20, 2025",
    amount: 48_600,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20013",
    customer: "Beta Ltd.",
    invoiceDate: "Apr 18, 2025",
    dueDate: "May 18, 2025",
    amount: 124_800,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20012",
    customer: "Tech Solutions Inc.",
    invoiceDate: "Apr 16, 2025",
    dueDate: "May 16, 2025",
    amount: 4_500,
    status: "Canceled",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20011",
    customer: "Acme Corp.",
    invoiceDate: "Apr 14, 2025",
    dueDate: "May 14, 2025",
    amount: 92_000,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20010",
    customer: "Delta Enterprises",
    invoiceDate: "Apr 12, 2025",
    dueDate: "May 12, 2025",
    amount: 17_800,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20009",
    customer: "Omega Pvt. Ltd.",
    invoiceDate: "Apr 10, 2025",
    dueDate: "May 10, 2025",
    amount: 6_200,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "CM-3000",
    customer: "Stellar Systems",
    invoiceDate: "Apr 8, 2025",
    dueDate: "Apr 8, 2025",
    amount: -1_500,
    status: "Credit Memo",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20007",
    customer: "Prime Retailers",
    invoiceDate: "Apr 6, 2025",
    dueDate: "May 6, 2025",
    amount: 19_750,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20006",
    customer: "Visionary Works",
    invoiceDate: "Apr 4, 2025",
    dueDate: "May 4, 2025",
    amount: 48_600,
    status: "Paid",
    dueAmount: 0,
  },
  {
    invoiceNo: "INV-20005",
    customer: "Global Industries Ltd.",
    invoiceDate: "Apr 2, 2025",
    dueDate: "May 2, 2025",
    amount: 3_180,
    status: "Paid",
    dueAmount: 0,
  },
];

export const arCustomerDirectory: Record<
  string,
  {
    id: string;
    category: string;
    email: string;
    phone: string;
    paymentTerms: string;
    status: "Active" | "Inactive";
  }
> = {
  "Acme Corp.": {
    id: "CUST-201",
    category: "Automotive",
    email: "billing@acmecorp.com",
    phone: "+1 555-0201",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Global Industries Ltd.": {
    id: "CUST-202",
    category: "Manufacturing",
    email: "ap@globalindustries.com",
    phone: "+1 555-0202",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Tech Solutions Inc.": {
    id: "CUST-203",
    category: "Technology",
    email: "finance@techsolutions.com",
    phone: "+1 555-0203",
    paymentTerms: "Net 45",
    status: "Active",
  },
  "Beta Ltd.": {
    id: "CUST-204",
    category: "Retail",
    email: "accounts@betaltd.com",
    phone: "+1 555-0204",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Delta Enterprises": {
    id: "CUST-205",
    category: "Logistics",
    email: "billing@deltaenterprises.com",
    phone: "+1 555-0205",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Omega Pvt. Ltd.": {
    id: "CUST-206",
    category: "Manufacturing",
    email: "ap@omegapvt.com",
    phone: "+1 555-0206",
    paymentTerms: "Net 15",
    status: "Active",
  },
  "Bright Future LLC": {
    id: "CUST-207",
    category: "Retail",
    email: "accounts@brightfuture.com",
    phone: "+1 555-0207",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Stellar Systems": {
    id: "CUST-208",
    category: "Technology",
    email: "billing@stellarsystems.com",
    phone: "+1 555-0208",
    paymentTerms: "Net 30",
    status: "Active",
  },
  "Prime Retailers": {
    id: "CUST-209",
    category: "Retail",
    email: "ap@primeretailers.com",
    phone: "+1 555-0209",
    paymentTerms: "Net 15",
    status: "Active",
  },
  "Visionary Works": {
    id: "CUST-210",
    category: "Consulting",
    email: "finance@visionaryworks.com",
    phone: "+1 555-0210",
    paymentTerms: "Net 30",
    status: "Active",
  },
};

/* -------- Legacy / supporting data for other routes -------- */
export const kpis = {
  totalRevenue: 24_580_000,
  todayRevenue: 184_250,
  monthlyRevenue: 3_420_000,
  pendingPayments: 1_245_600,
  expenses: 18_760_000,
  netProfit: 4_320_000,
  profitMargin: 17.6,
  outstandingReceivables: 7_650_000,
  outstandingPayables: 5_420_000,
  cashBalance: 6_780_000,
};

export const revenueTrend = revenueExpenseTrend.map((r) => ({
  month: r.month.split(" ")[0],
  revenue: r.revenue,
  expenses: r.expenses,
}));

export const revenueSources = [
  { name: "Vehicle Sales", value: 14_200_000, color: "#0A3C75" },
  { name: "Service & Maintenance", value: 4_850_000, color: "#336B9F" },
  { name: "Charging Network", value: 3_620_000, color: "#729FC9" },
  { name: "Accessories & Parts", value: 1_910_000, color: "#E2D9C5" },
];

export const revenueByStation = [
  { station: "Bengaluru – Whitefield Hub", revenue: 4_820_000, sessions: 8420 },
  { station: "Mumbai – BKC Tower", revenue: 4_310_000, sessions: 7180 },
  { station: "Delhi – Aerocity Plaza", revenue: 3_950_000, sessions: 6720 },
  { station: "Hyderabad – HITEC City", revenue: 3_580_000, sessions: 6240 },
  { station: "Pune – Hinjewadi Park", revenue: 3_120_000, sessions: 5410 },
  { station: "Chennai – OMR Tech Park", revenue: 2_880_000, sessions: 4980 },
  { station: "Gurugram – Cyber Hub", revenue: 2_640_000, sessions: 4520 },
  { station: "Ahmedabad – SG Road", revenue: 2_210_000, sessions: 3840 },
];

export const expenseCategories = [
  { category: "Cost of Goods Sold", amount: 6_566_000, color: "#0A3C75" },
  { category: "Operating Expenses", amount: 4_690_000, color: "#336B9F" },
  { category: "Employee Expenses", amount: 3_752_000, color: "#729FC9" },
  { category: "Marketing & Sales", amount: 1_876_000, color: "#B2C9DF" },
  { category: "Other Expenses", amount: 1_876_000, color: "#E2D9C5" },
];

export const expenses = [
  {
    id: "EXP-2025-0142",
    date: "2025-03-26",
    category: "Cost of Goods Sold",
    vendor: "Panasonic Cells",
    amount: 248_000,
    status: "Paid" as const,
  },
  {
    id: "EXP-2025-0141",
    date: "2025-03-25",
    category: "Operating Expenses",
    vendor: "DLF Properties",
    amount: 84_500,
    status: "Pending" as const,
  },
  {
    id: "EXP-2025-0140",
    date: "2025-03-24",
    category: "Marketing & Sales",
    vendor: "BrandMatter Studio",
    amount: 92_500,
    status: "Paid" as const,
  },
  {
    id: "EXP-2025-0139",
    date: "2025-03-22",
    category: "Employee Expenses",
    vendor: "Payroll – March",
    amount: 320_000,
    status: "Paid" as const,
  },
  {
    id: "EXP-2025-0138",
    date: "2025-03-20",
    category: "Other Expenses",
    vendor: "Siemens India",
    amount: 68_400,
    status: "Approved" as const,
  },
  {
    id: "EXP-2025-0137",
    date: "2025-03-18",
    category: "Marketing & Sales",
    vendor: "Google Ads",
    amount: 45_000,
    status: "Paid" as const,
  },
  {
    id: "EXP-2025-0136",
    date: "2025-03-15",
    category: "Cost of Goods Sold",
    vendor: "Bosch Components",
    amount: 184_000,
    status: "Paid" as const,
  },
  {
    id: "EXP-2025-0135",
    date: "2025-03-12",
    category: "Other Expenses",
    vendor: "Office Supplies Co.",
    amount: 24_800,
    status: "Pending" as const,
  },
];

export const receivables = [
  {
    invoice: "INV-9821",
    customer: "Acme Corp.",
    amount: 482_500,
    due: "2025-04-04",
    status: "Overdue" as const,
    days: 6,
  },
  {
    invoice: "INV-9820",
    customer: "Beta Ltd.",
    amount: 318_900,
    due: "2025-04-10",
    status: "Pending" as const,
    days: 0,
  },
  {
    invoice: "INV-9819",
    customer: "Gamma Industries",
    amount: 624_000,
    due: "2025-04-12",
    status: "Pending" as const,
    days: 0,
  },
  {
    invoice: "INV-9818",
    customer: "Delta Mobility",
    amount: 184_200,
    due: "2025-03-28",
    status: "Overdue" as const,
    days: 12,
  },
  {
    invoice: "INV-9817",
    customer: "Epsilon Fleet",
    amount: 920_000,
    due: "2025-04-18",
    status: "Pending" as const,
    days: 0,
  },
  {
    invoice: "INV-9816",
    customer: "Zeta Logistics",
    amount: 285_600,
    due: "2025-03-30",
    status: "Paid" as const,
    days: 0,
  },
];

export const payables = [
  {
    invoice: "BILL-40011",
    vendor: "Global Services",
    amount: 7_850,
    due: "2025-04-05",
    status: "Pending" as const,
  },
  {
    invoice: "BILL-40010",
    vendor: "ABC Supplies",
    amount: 12_450,
    due: "2025-04-08",
    status: "Pending" as const,
  },
  {
    invoice: "BILL-40009",
    vendor: "Siemens India",
    amount: 68_400,
    due: "2025-04-15",
    status: "Approved" as const,
  },
  {
    invoice: "BILL-40008",
    vendor: "ABB Power Grids",
    amount: 412_000,
    due: "2025-03-30",
    status: "Paid" as const,
  },
  {
    invoice: "BILL-40007",
    vendor: "Delta Electronics",
    amount: 295_000,
    due: "2025-04-12",
    status: "Pending" as const,
  },
  {
    invoice: "BILL-40006",
    vendor: "Schneider Electric",
    amount: 178_000,
    due: "2025-03-28",
    status: "Paid" as const,
  },
];

export const ledger = [
  {
    date: "2025-03-26",
    ref: "JV-1042",
    desc: "Revenue – Vehicle delivery batch #341",
    debit: 0,
    credit: 184_250,
    balance: 6_780_000,
  },
  {
    date: "2025-03-26",
    ref: "JV-1041",
    desc: "COGS – Battery cell procurement",
    debit: 248_000,
    credit: 0,
    balance: 6_595_750,
  },
  {
    date: "2025-03-25",
    ref: "JV-1040",
    desc: "Revenue – Service contract",
    debit: 0,
    credit: 624_000,
    balance: 6_843_750,
  },
  {
    date: "2025-03-25",
    ref: "JV-1039",
    desc: "Operating – Facility lease",
    debit: 84_500,
    credit: 0,
    balance: 6_219_750,
  },
  {
    date: "2025-03-24",
    ref: "JV-1038",
    desc: "Revenue – Charging network",
    debit: 0,
    credit: 920_000,
    balance: 6_304_250,
  },
  {
    date: "2025-03-24",
    ref: "JV-1037",
    desc: "Marketing – Campaign Q1",
    debit: 92_500,
    credit: 0,
    balance: 5_384_250,
  },
  {
    date: "2025-03-22",
    ref: "JV-1036",
    desc: "Payroll – March",
    debit: 320_000,
    credit: 0,
    balance: 5_476_750,
  },
  {
    date: "2025-03-22",
    ref: "JV-1035",
    desc: "Other – Misc settlement",
    debit: 0,
    credit: 142_000,
    balance: 5_796_750,
  },
];

export const assets = [
  {
    id: "AST-1042",
    name: "Stamping Press – Plant 1",
    type: "Machinery",
    station: "Bengaluru Plant",
    cost: 4_820_000,
    depreciated: 482_000,
    status: "Operational" as const,
  },
  {
    id: "AST-1041",
    name: "Battery Assembly Line A",
    type: "Machinery",
    station: "Bengaluru Plant",
    cost: 3_920_000,
    depreciated: 392_000,
    status: "Operational" as const,
  },
  {
    id: "AST-1040",
    name: "Paint Booth – Line 2",
    type: "Machinery",
    station: "Pune Plant",
    cost: 480_000,
    depreciated: 96_000,
    status: "Maintenance" as const,
  },
  {
    id: "AST-1039",
    name: "Test Track Equipment",
    type: "Equipment",
    station: "R&D Center",
    cost: 2_680_000,
    depreciated: 268_000,
    status: "Operational" as const,
  },
  {
    id: "AST-1038",
    name: "Robotic Welding Arm #4",
    type: "Machinery",
    station: "Bengaluru Plant",
    cost: 1_840_000,
    depreciated: 184_000,
    status: "Operational" as const,
  },
  {
    id: "AST-1037",
    name: "Office Fitout – HQ",
    type: "Office Asset",
    station: "HQ",
    cost: 1_240_000,
    depreciated: 248_000,
    status: "Operational" as const,
  },
];

export const vendors = [
  {
    id: "VND-001",
    name: "Panasonic Cells",
    category: "Batteries",
    outstanding: 1_248_000,
    status: "Active" as const,
    rating: 4.6,
  },
  {
    id: "VND-002",
    name: "Bosch Components",
    category: "Electronics",
    outstanding: 184_500,
    status: "Active" as const,
    rating: 4.4,
  },
  {
    id: "VND-003",
    name: "Siemens India",
    category: "Equipment",
    outstanding: 68_400,
    status: "Active" as const,
    rating: 4.8,
  },
  {
    id: "VND-004",
    name: "ABB Power Grids",
    category: "Equipment",
    outstanding: 0,
    status: "Active" as const,
    rating: 4.9,
  },
  {
    id: "VND-005",
    name: "Delta Electronics",
    category: "Electronics",
    outstanding: 295_000,
    status: "Active" as const,
    rating: 4.5,
  },
  {
    id: "VND-006",
    name: "DLF Properties",
    category: "Facilities",
    outstanding: 0,
    status: "Active" as const,
    rating: 4.2,
  },
];

export const stations = [
  {
    id: "STN-01",
    name: "Whitefield Hub",
    city: "Bengaluru",
    chargers: 12,
    uptime: 99.4,
    todayRevenue: 38_420,
    status: "Online" as const,
  },
  {
    id: "STN-02",
    name: "BKC Tower",
    city: "Mumbai",
    chargers: 10,
    uptime: 98.8,
    todayRevenue: 31_240,
    status: "Online" as const,
  },
  {
    id: "STN-03",
    name: "Aerocity Plaza",
    city: "Delhi",
    chargers: 8,
    uptime: 97.2,
    todayRevenue: 24_180,
    status: "Online" as const,
  },
  {
    id: "STN-04",
    name: "HITEC City",
    city: "Hyderabad",
    chargers: 10,
    uptime: 99.1,
    todayRevenue: 28_640,
    status: "Online" as const,
  },
  {
    id: "STN-05",
    name: "Hinjewadi Park",
    city: "Pune",
    chargers: 6,
    uptime: 95.8,
    todayRevenue: 18_420,
    status: "Degraded" as const,
  },
  {
    id: "STN-06",
    name: "OMR Tech Park",
    city: "Chennai",
    chargers: 8,
    uptime: 99.0,
    todayRevenue: 21_580,
    status: "Online" as const,
  },
  {
    id: "STN-07",
    name: "Cyber Hub",
    city: "Gurugram",
    chargers: 6,
    uptime: 0,
    todayRevenue: 0,
    status: "Offline" as const,
  },
];

export const users = [
  {
    id: "USR-001",
    name: "Aarav Mehta",
    email: "aarav@magnertia.com",
    role: "Super Admin",
    lastActive: "2 min ago",
    status: "Active" as const,
  },
  {
    id: "USR-002",
    name: "Priya Sharma",
    email: "priya@magnertia.com",
    role: "Finance Manager",
    lastActive: "1 hr ago",
    status: "Active" as const,
  },
  {
    id: "USR-003",
    name: "Rohan Iyer",
    email: "rohan@magnertia.com",
    role: "Operations Manager",
    lastActive: "3 hr ago",
    status: "Active" as const,
  },
  {
    id: "USR-004",
    name: "Neha Kapoor",
    email: "neha@magnertia.com",
    role: "Accountant",
    lastActive: "Yesterday",
    status: "Active" as const,
  },
  {
    id: "USR-005",
    name: "Vikram Singh",
    email: "vikram@magnertia.com",
    role: "Auditor",
    lastActive: "2 days ago",
    status: "Inactive" as const,
  },
  {
    id: "USR-006",
    name: "Ananya Rao",
    email: "ananya@magnertia.com",
    role: "Viewer",
    lastActive: "5 days ago",
    status: "Active" as const,
  },
];

export function formatCurrency(n: number, compact = false) {
  const sign = n < 0 ? "-" : "";
  const v = Math.abs(n);
  if (compact) {
    if (v >= 1_000_000) {
      const millions = (v / 1_000_000).toLocaleString("en-US", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      });
      return `${sign}$${millions}M`;
    }
    if (v >= 1_000) return `${sign}$${(v / 1_000).toFixed(1)}K`;
  }
  return `${sign}$${v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function formatSignedCurrency(n: number, compact = false) {
  if (n < 0) {
    const inner = formatCurrency(Math.abs(n), compact).replace("-", "");
    return `(${inner})`;
  }
  return formatCurrency(n, compact);
}
