import { Package, Layers, Rocket, Repeat, Activity } from "lucide-react";
import type { WidgetDefinition } from "../../types";
import { makeStatCardWidget } from "../shared/StatCardWidget";

export const pdWidgets: WidgetDefinition[] = [
  makeStatCardWidget({
    id: "kpi.pd.active-projects",
    title: "Active Projects",
    description: "Total active product engineering projects across design and build stages.",
    category: "kpi",
    icon: Package,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
    options: () => ({ queryKey: ["pd", "active-projects"], queryFn: async () => ({ value: 18, statusText: "+3 this month" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 18), delta: { label: "+3 this month", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.in-development",
    title: "In Development",
    description: "Products currently undergoing detailed mechanical, electrical & software engineering.",
    category: "kpi",
    icon: Layers,
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-500",
    options: () => ({ queryKey: ["pd", "in-development"], queryFn: async () => ({ value: 12, statusText: "On schedule" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 12), delta: { label: "On schedule", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.ready-release",
    title: "Ready for Release",
    description: "Products passing validation and awaiting release gate approval.",
    category: "kpi",
    icon: Rocket,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["pd", "ready-release"], queryFn: async () => ({ value: 4, statusText: "1 pending review" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 4), delta: { label: "1 pending review", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.active-lifecycle",
    title: "In Active Lifecycle",
    description: "Products in active commercial lifecycle with active digital thread tracking.",
    category: "kpi",
    icon: Repeat,
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-500",
    options: () => ({ queryKey: ["pd", "active-lifecycle"], queryFn: async () => ({ value: 34, statusText: "ECR/ECO active" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 34), delta: { label: "ECR/ECO active", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.pd.overall-health",
    title: "Overall Product Health",
    description: "Aggregate engineering quality, schedule compliance, and requirement satisfaction score.",
    category: "kpi",
    icon: Activity,
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-500",
    options: () => ({ queryKey: ["pd", "overall-health"], queryFn: async () => ({ value: "94%", statusText: "Optimal quality" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "94%"), delta: { label: "Optimal quality", direction: "up", tone: "positive" } }),
  }),
];
