/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as ProfitabilityRouteImport } from './routes/profitability'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CostCentersRouteImport } from './routes/cost-centers'
import { Route as ConsolidationRouteImport } from './routes/consolidation'
import { Route as CashBankRouteImport } from './routes/cash-bank'
import { Route as BudgetingRouteImport } from './routes/budgeting'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityRoute = ProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCentersRoute = CostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidationRoute = ConsolidationRouteImport.update({
  id: '/consolidation',
  path: '/consolidation',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBankRoute = CashBankRouteImport.update({
  id: '/cash-bank',
  path: '/cash-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingRoute = BudgetingRouteImport.update({
  id: '/budgeting',
  path: '/budgeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/budgeting': typeof BudgetingRoute
  '/cash-bank': typeof CashBankRoute
  '/consolidation': typeof ConsolidationRoute
  '/cost-centers': typeof CostCentersRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/overview': typeof OverviewRoute
  '/payables': typeof PayablesRoute
  '/profitability': typeof ProfitabilityRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/budgeting': typeof BudgetingRoute
  '/cash-bank': typeof CashBankRoute
  '/consolidation': typeof ConsolidationRoute
  '/cost-centers': typeof CostCentersRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/overview': typeof OverviewRoute
  '/payables': typeof PayablesRoute
  '/profitability': typeof ProfitabilityRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/budgeting': typeof BudgetingRoute
  '/cash-bank': typeof CashBankRoute
  '/consolidation': typeof ConsolidationRoute
  '/cost-centers': typeof CostCentersRoute
  '/expenses': typeof ExpensesRoute
  '/ledger': typeof LedgerRoute
  '/overview': typeof OverviewRoute
  '/payables': typeof PayablesRoute
  '/profitability': typeof ProfitabilityRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/stations': typeof StationsRoute
  '/tax': typeof TaxRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/audit'
    | '/budgeting'
    | '/cash-bank'
    | '/consolidation'
    | '/cost-centers'
    | '/expenses'
    | '/ledger'
    | '/overview'
    | '/payables'
    | '/profitability'
    | '/receivables'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/stations'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/audit'
    | '/budgeting'
    | '/cash-bank'
    | '/consolidation'
    | '/cost-centers'
    | '/expenses'
    | '/ledger'
    | '/overview'
    | '/payables'
    | '/profitability'
    | '/receivables'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/stations'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/audit'
    | '/budgeting'
    | '/cash-bank'
    | '/consolidation'
    | '/cost-centers'
    | '/expenses'
    | '/ledger'
    | '/overview'
    | '/payables'
    | '/profitability'
    | '/receivables'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/stations'
    | '/tax'
    | '/transactions'
    | '/users'
    | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AuditRoute: typeof AuditRoute
  BudgetingRoute: typeof BudgetingRoute
  CashBankRoute: typeof CashBankRoute
  ConsolidationRoute: typeof ConsolidationRoute
  CostCentersRoute: typeof CostCentersRoute
  ExpensesRoute: typeof ExpensesRoute
  LedgerRoute: typeof LedgerRoute
  OverviewRoute: typeof OverviewRoute
  PayablesRoute: typeof PayablesRoute
  ProfitabilityRoute: typeof ProfitabilityRoute
  ReceivablesRoute: typeof ReceivablesRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  StationsRoute: typeof StationsRoute
  TaxRoute: typeof TaxRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability': {
      id: '/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof ProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-centers': {
      id: '/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof CostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidation': {
      id: '/consolidation'
      path: '/consolidation'
      fullPath: '/consolidation'
      preLoaderRoute: typeof ConsolidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-bank': {
      id: '/cash-bank'
      path: '/cash-bank'
      fullPath: '/cash-bank'
      preLoaderRoute: typeof CashBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting': {
      id: '/budgeting'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof BudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AuditRoute: AuditRoute,
  BudgetingRoute: BudgetingRoute,
  CashBankRoute: CashBankRoute,
  ConsolidationRoute: ConsolidationRoute,
  CostCentersRoute: CostCentersRoute,
  ExpensesRoute: ExpensesRoute,
  LedgerRoute: LedgerRoute,
  OverviewRoute: OverviewRoute,
  PayablesRoute: PayablesRoute,
  ProfitabilityRoute: ProfitabilityRoute,
  ReceivablesRoute: ReceivablesRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  StationsRoute: StationsRoute,
  TaxRoute: TaxRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
