import { Settings, Repeat, ShieldCheck, Rocket, Gauge } from "lucide-react";
import type { WidgetDefinition } from "../../types";
import { makeStatCardWidget } from "../shared/StatCardWidget";

export const mdWidgets: WidgetDefinition[] = [
  makeStatCardWidget({
    id: "kpi.md.active-projects",
    title: "Active Mfg Projects",
    description: "Total active manufacturing engineering and industrialization projects.",
    category: "kpi",
    icon: Settings,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
    options: () => ({ queryKey: ["md", "active-projects"], queryFn: async () => ({ value: 15, statusText: "+2 this quarter" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 15), delta: { label: "+2 this quarter", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.md.in-pilot",
    title: "In Pilot Production",
    description: "Line trial runs and pilot production builds underway.",
    category: "kpi",
    icon: Repeat,
    iconBg: "bg-amber-500/10",
    iconColor: "text-amber-500",
    options: () => ({ queryKey: ["md", "in-pilot"], queryFn: async () => ({ value: 5, statusText: "Average yield 98.2%" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 5), delta: { label: "Average yield 98.2%", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.md.ready-ppap",
    title: "Ready for PPAP",
    description: "Process validation complete and ready for PPAP submission.",
    category: "kpi",
    icon: ShieldCheck,
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-500",
    options: () => ({ queryKey: ["md", "ready-ppap"], queryFn: async () => ({ value: 3, statusText: "Level 3 submission" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 3), delta: { label: "Level 3 submission", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.md.mass-production",
    title: "In Mass Production",
    description: "Full rate mass production lines operating under control plans.",
    category: "kpi",
    icon: Rocket,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-500",
    options: () => ({ queryKey: ["md", "mass-production"], queryFn: async () => ({ value: 28, statusText: "OEE 89.4%" }) }),
    map: (data: any) => ({ value: String(data?.value ?? 28), delta: { label: "OEE 89.4%", direction: "up", tone: "positive" } }),
  }),
  makeStatCardWidget({
    id: "kpi.md.overall-readiness",
    title: "Overall Mfg Readiness",
    description: "Aggregate manufacturing readiness score across tooling, process, and quality.",
    category: "kpi",
    icon: Gauge,
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-500",
    options: () => ({ queryKey: ["md", "overall-readiness"], queryFn: async () => ({ value: "92%", statusText: "Target MRL 8+" }) }),
    map: (data: any) => ({ value: String(data?.value ?? "92%"), delta: { label: "Target MRL 8+", direction: "up", tone: "positive" } }),
  }),
];
